name: Deploy Web App
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      
jobs:
  build:
    name: Build
    uses: pied-piper-inc/popular-repos-web-app/.github/workflows/build-image.yml@main

  deploy:
    needs: build
    uses 
  deploy_to_review:
    name: Deploy Review
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    environment: 
      name: review-lab
      url: ${{ steps.popular-repos-web.outputs.webapp-url }}
    needs: build
    steps:
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_SUBSCRIPTION_SECRET }}

    - name: Create deployment slot
      run: |
        az webapp deployment slot create --name popular-repos --resource-group pied-piper-inc --slot review-pr-${{ github.event.number }} --configuration-source popular-repos

    - name: Deploy popular repos
      uses: azure/webapps-deploy@v2
      id: popular-repos-web
      with:
        app-name: 'popular-repos'
        images: '${{ secrets.AZURE_REGISTRY_NAME }}/popular-repos:${{ github.event.pull_request.head.sha }}'
        slot-name: review-pr-${{ github.event.number }}

  deploy_to_staging:
    name: Deploy Staging
    if: github.event.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: 
      name: staging
      url: ${{ steps.popular-repos-web.outputs.webapp-url }}
    concurrency: staging
    needs: build
    steps:
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_SUBSCRIPTION_SECRET }}

    - name: Deploy popular repos
      uses: azure/webapps-deploy@v2
      id: popular-repos-web
      with:
        app-name: 'popular-repos'
        images: '${{ secrets.AZURE_REGISTRY_NAME }}/popular-repos:${{ github.sha }}'
        slot-name: staging

  deploy_to_production:
    name: Deploy Production
    if: github.event.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: https://popular-repos.azurewebsites.net
    concurrency: production
    needs: deploy_to_staging
    steps:
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_SUBSCRIPTION_SECRET }}

    - name: Swap staging to production
      run: |
        az webapp deployment slot swap --name popular-repos --resource-group pied-piper-inc --slot staging --target-slot production